### ISSUE TITLE
Creating new datastore on startup of HDS

### ISSUE THREAD

**Issue by aminrahman** [linksmart/historical-datastore#59]
I use <code>sudo docker run -p 8085:8085 linksmart/hds</code> to start my HDS service. But every time that HDS starts and I call /registry API, a new datastore gets created. How can I reuse the ones that already are created?

**Comment by aminrahman** [comment]
I forgot to mention that I use it on Raspbian OS on a Raspberry pi. I installed my HDS by running <code>docker build -t linksmart/hds </code> in the directory of downloaded image.

**Comment by farshidtz** [comment]
Hi Amin,

`docker run` creates and starts a new container. Since the data within the container is not mounted, you are creating a new database every time you run it, without removing the old containers.

You need to mount the `/data` volume to host in order to add persistency. E.g. to mount on `./mydata` relative to execution path:
```
docker run -p 8085:8085 -v $(pwd)/mydata:/data --name hds linksmart/hds
```
You may add `-d` argument to run it in detached mode.  

Then, you can stop|start|restart it this way:
```
docker stop|start|restart hds
```

Get the logs and follow:
```
docker logs hds -f
```

These are the basics but you need to read more about docker if you want to run HDS in long term.

**Comment by farshidtz** [comment]
@dschowta please document how to persist the HDS data.
